name: Build and upload Wheel to PyPI

on:
  release:
    types: [published]
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build pure Python wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]  # Full set of Python versions
    steps:
      - uses: actions/checkout@v4

      # Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}  # Set Python version from matrix

      # Conditionally skip macOS for Python versions < 3.11
      - name: Skip macOS for Python < 3.11
        if: runner.os == 'macos-latest' && (matrix.python-version == '3.8' || matrix.python-version == '3.9' || matrix.python-version == '3.10')
        run: |
          echo "Skipping macOS for Python ${matrix.python-version}, as it is less than 3.11."

      # Install build tools
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      # Build the wheel
      - name: Build pure Python wheel
        run: |
          python -m pip wheel --no-deps --wheel-dir=wheelhouse .

      # Rename the wheels for Windows separately
      - name: Rename wheel for Windows
        if: runner.os == 'Windows'
        run: |
          set python_version=${{ matrix.python-version }}
          set wheel_name=wheelhouse\*.whl
          set base_name=%~nXw

          # Rename based on Python version and architecture
          if "%python_version%"=="3.8" (
            ren "%wheel_name%" "%base_name%-cp38-win32.whl"
            ren "%wheel_name%" "%base_name%-cp38-win_amd64.whl"  # Also support 64-bit for 3.8
          ) else if "%python_version%"=="3.9" (
            ren "%wheel_name%" "%base_name%-cp39-win32.whl"
            ren "%wheel_name%" "%base_name%-cp39-win_amd64.whl"  # Also support 64-bit for 3.9
          ) else if "%python_version%"=="3.10" (
            ren "%wheel_name%" "%base_name%-cp310-win32.whl"
            ren "%wheel_name%" "%base_name%-cp310-win_amd64.whl"  # Also support 64-bit for 3.10
          ) else if "%python_version%"=="3.11" (
            ren "%wheel_name%" "%base_name%-cp311-win_amd64.whl"
          ) else if "%python_version%"=="3.12" (
            ren "%wheel_name%" "%base_name%-cp312-win_amd64.whl"
          )

          del "%wheel_name%"


      # Rename Linux/macOS wheels
      - name: Rename wheel for Linux/macOS
        if: runner.os != 'Windows'
        run: |
          python_version="${{ matrix.python-version }}"
          platform=$(uname -s | tr '[:upper:]' '[:lower:]')  # Detect platform (e.g., 'linux', 'darwin')
          wheel_name=wheelhouse/*.whl

          if [[ "$platform" == "linux" ]]; then
            mv "$wheel_name" "${wheelhouse}/$(basename "$wheel_name" .whl)-cp${python_version//./}-manylinux_2_28_x86_64.whl"
          elif [[ "$platform" == "darwin" ]]; then
            mv "$wheel_name" "${wheelhouse}/$(basename "$wheel_name" .whl)-cp${python_version//./}-macos.whl"
          fi


      # Upload the built wheels as artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: pure-python-wheel-${{ matrix.os }}-${{ matrix.python-version }}
          path: ./wheelhouse/*.whl

  upload_pypi:
    name: Upload to PyPI
    needs: build_wheels
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: pure-python-wheel-*
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
